// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvdovkgggbtcntljaebu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZG92a2dnZ2J0Y250bGphZWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzI5ODIsImV4cCI6MjA2MTYwODk4Mn0.6FfSf27lDHW0DuQDsNQ4wOt9HArpqnoFkPb732YhbW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);